# Generated by Django 4.1.4 on 2022-12-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='precio',
            new_name='price',
        ),
    ]
