# Generated by Django 4.1.4 on 2022-12-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category'),
        ('products', '0004_family'),
    ]

    operations = [
    ]
